# baseURL = 'http://aedhr.com'
baseURL = 'https://aed-hr.onrender.com/'
languageCode = 'en-us'
title = "aed HR" #changes the title on the home page
theme = "ava" #don't change this, it will stop working
paginate = 7
mainSections = "post"

enableEmoji = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  ga_id=""
  mainSections = ["post"]
  disqus = "xxxxxxx"
  defaultImage = "/images/frontpage.png"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        tabWidth = 4
        noClasses = false
        pygmentsUseClasses = true
        pygmentsCodefences = true

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true   

    [markup.blackFriday]
        angledQuotes = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3

[[menu.main]]
    name = "Working Together"
    url = "/working-together/"
    weight = 4

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:filename/"